import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header/Header'
import { collection, doc, getDoc, getDocs } from 'firebase/firestore'
import { db } from '@/firebaseConfig'
import Link from 'next/link'
import { useState } from 'react'
import LessonCard from '@/components/LessonCard/LessonCard'

const subjectsArray = [
  {
    id: 2,
    subjectName: "Rockets",
    subjectLogo: "w",
    subjectCoverImage: "w",
    ref: "rockets"
  },
  {
    id: 0,
    subjectName: "Planets",
    subjectLogo: "w",
    subjectCoverImage: "w",
    ref: "planets"
  },
  {
    id: 1,
    subjectName: "Aliens",
    subjectLogo: "w",
    subjectCoverImage: "w",
    ref: "aliens"
  },
]


export default function Home({ rocketData, lessonTestsData , lessonFirstTestQuestionsAndAnswersData, lessonData}: any) {

  const [selectedSubject, setSelectedSubject] = useState<string>("rockets")
  // const [selectedSubjectLessonsData, setSelectedSubjectLessonsData] = useState<any[]>(physicsData)




  return (
    <>
      <Head>
        <title>Astro Verse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-Lightest col-span-full lg:col-start-3 lg:col-end-13 flex flex-col items-center justify-start px-10'>
        <Header />

        {/* Subjects Container*/}
        <div className='w-full flex flex-col justify-start items-start my-10'>

          <h6 className='text-4xl text-Dark font-nunito font-bold'> Subjects </h6>

          <div className='w-full flex flex-wrap justify-start items-center my-5'>
            {subjectsArray?.map((subject) => {
              return (
                <div
                  onClick={() => {
                    setSelectedSubject(subject.ref)
                  }}
                  key={subject.id}
                  className={`w-32 h-32 md:w-52 md:h-52 rounded-lg ${subject.subjectName === "Rockets" && "bg-gray-200"} ${subject.subjectName === "Planets" && "bg-blue-100"} ${subject.subjectName === "Aliens" && "bg-green-200"} flex justify-end items-end p-5 hover:cursor-pointer m-2 ${selectedSubject === subject.ref && "border-4 border-Brand"}`}>
                  <h5 className='text-lg md:text-3xl text-Dark font-nunito font-semibold'> {subject.subjectName} </h5>
                </div>
              )
            })}
          </div>
        </div>

        {/* Lessons Container */}
        <div className='w-full flex flex-col justify-start items-start my-10'>

          <span className='w-full'>
            <span onClick={() =>{
               console.log(lessonData)
               console.log(lessonTestsData)
               console.log(lessonFirstTestQuestionsAndAnswersData)
            }} className='text-4xl text-Dark font-nunito font-bold '> <span className='text-4xl text-Brand font-nunito font-bold'> MetaVerse </span> Classes - {selectedSubject} </span>

          </span>

          <div className='w-full flex flex-col justify-start items-center my-5 space-y-5'>

            <div className='w-full flex flex-col items-center justify-start space-y-3'>
              {rocketData?.map((lesson: any) => {
                return <LessonCard key={lesson?.lessonID} lesson={lesson} />
              })}
            </div>

            <div className='w-full flex flex-col items-center justify-start space-y-3'>
              {rocketData?.map((lesson: any) => {
                return <LessonCard key={lesson?.lessonID} lesson={lesson} />
              })}
            </div>










          </div>
        </div>

      </main>
    </>
  )
}


export async function getServerSideProps() {

  // Getting rocket lessons -> class 10th
  const rocketLessonsCollectionRef = collection(db, `classes/10/space_subjects/rockets/lessons`)
  const rocketRes = await getDocs(rocketLessonsCollectionRef)
  const rocketData = rocketRes?.docs?.map(doc => doc.data())


  const lessonRef = doc(db, "classes", "10", "space_subjects", `rockets`, 'lessons', `lbdhXTAbh81xU1x5iwY0`)
  const lessonRes = await getDoc(lessonRef)
  const lessonData = lessonRes.data() || null


  const lessonTestsCollectionRef = collection(db, "classes", "10", "space_subjects", `rockets`, 'lessons', `lbdhXTAbh81xU1x5iwY0`, "tests")
  const lessonTestsRes = await getDocs(lessonTestsCollectionRef)
  const lessonTestsData = lessonTestsRes?.docs?.map(doc => doc.data())

  const lessonFirstTestQuestionsAndAnswersRef = doc(db, "classes", "10", "space_subjects", `rockets`, 'lessons', `lbdhXTAbh81xU1x5iwY0`, "tests", `KyEwJIYs3CW9Kcqf9RyU`)
  const lessonFirstTestQuestionsAndAnswersRes = await getDoc(lessonFirstTestQuestionsAndAnswersRef)
  const lessonFirstTestQuestionsAndAnswersData = lessonFirstTestQuestionsAndAnswersRes?.data() || null


  return {
    props: { rocketData, lessonTestsData, lessonFirstTestQuestionsAndAnswersData, lessonData }
  }
}